# Generated by Django 5.1.3 on 2024-12-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Ivan', max_length=30)),
                ('patronymic', models.CharField(default='Ivanovich', max_length=30)),
                ('family', models.CharField(default='Ivanov', max_length=30)),
                ('city', models.CharField(default='Burevestnik', max_length=30)),
                ('age', models.IntegerField(default=18, max_length=3)),
                ('teams', models.ManyToManyField(default=None, related_name='teams', to='task1.team')),
            ],
        ),
    ]
