# Generated by Django 5.1.3 on 2024-11-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='buyer',
            field=models.ManyToManyField(default=None, related_name='games', to='task1.buyer'),
        ),
    ]
