# Generated by Django 5.1.3 on 2024-11-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_game_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='game',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(default='Play for free'),
        ),
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='Game', max_length=50),
        ),
    ]
